### ISSUE TITLE
Support more then "Data" section in the AMQP_PUBLISH message

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/mqtt-gateway#10]
If a message is published from a native AMQP client it could have an AMQP value as body so using the AMQP type system (i.e. simple type but even list, map, ...). It could be delivered to an MQTT client. Do we have to consider a different encoding in this case ? (i.e. JSON as body of the MQTT message)

**Comment by ppatierno** [comment]
@grs @lulf what do you think about that ?

**Comment by lulf** [comment]
This issue was moved to EnMasseProject/enmasse#64
