### ISSUE TITLE
Having non-TLS and TLS enabled MQTT server in the same MQTT gateway instance

### ISSUE THREAD

**Issue by ppatierno** [EnMasseProject/mqtt-gateway#28]
Instead of spinning up two different containers in the same mqtt pod for having non-TLS and TLS enabled mqtt server, we could have only one container and both mqtt server instance in the same mqtt gateway instance (i.e. see the Eclipse Hono approach for MQTT adapter)

**Comment by lulf** [comment]
This issue was moved to EnMasseProject/enmasse#61
